'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('products', [
      {
        name: 'Plunder',
        price: 3.00,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771320800/5340_sadgk1.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Plunder Schnecke',
        price: 3.00,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771320798/Plunder-Schnecke_junfnv.webp',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Gefüllter MUFFIN',
        price: 2.50,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771320799/istockphoto-172204782-612x612_e9opee.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Gefüllte DONUTS',
        price: 2.50,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771320798/doughnut-mit-rosa-zuckerguss-und-streuseln-auf-weissem-hintergrund-nahaufnahme-CSF017866_jc2s1c.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MUFFIN Vanille oder Schoko',
        price: 2.00,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771320799/Schokomuffin_ynxv3z.avif',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Müsliriegel',
        price: 2.00,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771320800/muesliriegel_e4e2pi.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Mars, Twix, Snickers, Bueno',
        price: 2.00,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771321973/twix-32er_fcjf8t.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'M&M\'s, Kit Kat, Skittles',
        price: 2.00,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771320799/KitKat_n5c8xd.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Tortenecken',
        price: 2.50,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771322060/Bildschirmfoto_2026-02-17_um_10.51.08_zqtkmr.png',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        name: 'Baumstämme',
        price: 2.50,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771322166/Bildschirmfoto_2026-02-17_um_10.51.15_pdx26v.png',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        name: 'Mannerschnitten',
        price: 2.50,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771320803/1700_neapolitaner_grosspkg_18er_v6k9hm.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Pringles',
        price: 3.00,
        category: 'Snack',
        available: true,
        imageUrl: 'https://res.cloudinary.com/dpe8gnfh4/image/upload/v1771320800/9648-1_pringles-original-40g-nejkafe-cz.jpg_oqgbii.webp',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('products', {
      name: [
        'Plunder',
        'Plunder Schnecke',
        'Gefüllter MUFFIN',
        'Gefüllte DONUTS',
        'MUFFIN Vanille oder Schoko',
        'Müsliriegel',
        'Mars, Twix, Snickers, Bueno',
        'M&M\'s, Kit Kat, Skittles',
        'Tortenecken, Baumstämme',
        'Mannerschnitten',
        'Pringles',
      ],
    });
  },
};
